version: 2

#Sources
sources:
  - name: sf_sample_data
    database: snowflake_sample_data
    schema: tpch_sf1
    tables:
      - name: customer
      - name: lineitem
      - name: nation
      - name: orders
      - name: part
      - name: partsupp
      - name: region
      - name: supplier

# Models
models:
- name: raw_customers
  description: Raw data customers